create table element (id varchar(255) not null, date varchar(255), parentid varchar(255), size integer, type varchar(255), url varchar(255), parent varchar(255), primary key (id));
alter table element add constraint FKomy2j64rifkmlrpy8jwlcsefd foreign key (parent) references element;
create table element (id varchar(255) not null, date varchar(255), parentid varchar(255), size integer, type varchar(255), url varchar(255), parent_id varchar(255), primary key (id));
alter table element add constraint FKbi8nutl8t8x95vgkln5nil4fo foreign key (parent_id) references element;
create table element (id varchar(255) not null, date varchar(255), parentid varchar(255), size integer, type varchar(255), url varchar(255), parent_id varchar(255), primary key (id));
alter table element add constraint FKbi8nutl8t8x95vgkln5nil4fo foreign key (parent_id) references element;
create table element (id varchar(255) not null, date varchar(255), parentid varchar(255), size integer, type varchar(255), url varchar(255), parent_id varchar(255), primary key (id));
alter table element add constraint FKbi8nutl8t8x95vgkln5nil4fo foreign key (parent_id) references element;
create table element (id varchar(255) not null, date varchar(255), parentid varchar(255), size integer, type varchar(255), url varchar(255), parent_id varchar(255), primary key (id));
alter table element add constraint FKbi8nutl8t8x95vgkln5nil4fo foreign key (parent_id) references element;
create table element (id varchar(255) not null, date varchar(255), parentid varchar(255), size integer, type varchar(255), url varchar(255), parent_id varchar(255), primary key (id));
alter table element add constraint FKbi8nutl8t8x95vgkln5nil4fo foreign key (parent_id) references element;
create table element (id varchar(255) not null, date varchar(255), parentid varchar(255), size integer, type varchar(255), url varchar(255), parent_id varchar(255), primary key (id));
alter table element add constraint FKbi8nutl8t8x95vgkln5nil4fo foreign key (parent_id) references element;
create table element (id varchar(255) not null, date varchar(255), parentid varchar(255), size integer, type varchar(255), url varchar(255), parent_id varchar(255), primary key (id));
alter table element add constraint FKbi8nutl8t8x95vgkln5nil4fo foreign key (parent_id) references element;
create table element (id varchar(255) not null, date varchar(255), parentid varchar(255), size integer, type varchar(255), url varchar(255), parent_id varchar(255), primary key (id));
alter table element add constraint FKbi8nutl8t8x95vgkln5nil4fo foreign key (parent_id) references element;
create table element (id varchar(255) not null, date varchar(255), parentid varchar(255), size integer, type varchar(255), url varchar(255), parent_id varchar(255), primary key (id));
alter table element add constraint FKbi8nutl8t8x95vgkln5nil4fo foreign key (parent_id) references element;
create table element (id varchar(255) not null, date varchar(255), parentid varchar(255), size integer, type varchar(255), url varchar(255), parent_id varchar(255), primary key (id));
alter table element add constraint FKbi8nutl8t8x95vgkln5nil4fo foreign key (parent_id) references element;
create table element (id varchar(255) not null, date varchar(255), parentid varchar(255), size integer, type varchar(255), url varchar(255), parent_id varchar(255), primary key (id));
alter table element add constraint FKbi8nutl8t8x95vgkln5nil4fo foreign key (parent_id) references element;
create table element (id varchar(255) not null, date varchar(255), parentid varchar(255), size integer, type varchar(255), url varchar(255), parent_id varchar(255), primary key (id));
alter table element add constraint FKbi8nutl8t8x95vgkln5nil4fo foreign key (parent_id) references element;
create table element (id varchar(255) not null, date varchar(255), parentid varchar(255), size integer, type varchar(255), url varchar(255), parent_id varchar(255), primary key (id));
alter table element add constraint FKbi8nutl8t8x95vgkln5nil4fo foreign key (parent_id) references element;
create table element (id varchar(255) not null, date varchar(255), parentid varchar(255), size integer, type varchar(255), url varchar(255), parent_id varchar(255), primary key (id));
alter table element add constraint FKbi8nutl8t8x95vgkln5nil4fo foreign key (parent_id) references element;
